/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.MainUIController;

/**
 *
 * @author Joe
 */
public class AddNewStudentView extends javax.swing.JDialog {
    
    private MainUIController controller = null;
    /**
     * Creates new form AddNewTaskView
     */
    public AddNewStudentView(java.awt.Frame parent, boolean modal, MainUIController controller) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
        //this.setResizable(false); if you want to keep it the same size (no ability to chance)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priorityComboBox = new javax.swing.JComboBox<>();
        closeButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add New Student");
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel2);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);

        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(descriptionTextField);

        jLabel4.setText("Priority");
        getContentPane().add(jLabel4);

        priorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Low" }));
        getContentPane().add(priorityComboBox);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String priority = "Low";
        if (this.priorityComboBox.getSelectedIndex() == 0){
            priority =  "High";
        }
        
        this.controller.addStudent(this.descriptionTextField.getText(), priority);
        //System.out.println("There are " + this.controller.getToDoModel().getSize() + " student(s) on the list"); error not sure why
    }//GEN-LAST:event_createButtonActionPerformed

    private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
        // add your handling code here:
    }//GEN-LAST:event_descriptionTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> priorityComboBox;
    // End of variables declaration//GEN-END:variables
}
